-- vim.api.nvim_create_user_command(
--   'Config',
--   function()
--     local telescope = require('telescope.builtin')
--
--     telescope.find_files({ cwd = "~/.config/nvim" })
--   end,
--   {}
-- )
--
--
-- vim.keymap.set("n", "<leader>fu", function ()
--    local telescope = require('telescope.builtin')
--
--   telescope.live_grep({
--    search_dirs =
--   })
--
--
-- end)
--

-- vim.key.set('n', '<leader>fu', function()
--   require('telescope').extensions.live_grep_args.live_grep_args()
-- end)
